---
profiles:
  - name: k3sinfra
    target: ./k3sinfra

input:
  secret:
    - name: REG_PWD
      description: Registry password

functions:
  - name: package
    description: creates the package containing automation for remote host execution
    run:
      - art build -t artisan-registry-nexus.apps.demo.openshiftdev.com/k3s/k3sinfra

  - name: push
    description: pushes the latest package
    run:
      - art push -u admin:${REG_PWD} artisan-registry-nexus.apps.demo.openshiftdev.com/k3s/k3sinfra
    input:
      secret:
        - REG_PWD
...
