---

- name: Build a cluster with HA control plane
  hosts: k3s_cluster
  vars_files:
    - vars/k3s_variables.yml
  #vars:
  #  k3s_registration_address: "{{ }}"
  #  k3s_become_for_all: true
  #  k3s_etcd_datastore: false
  #  k3s_release_version: v1.22.2+k3s2
  #  k3s_server:
  #    datastore-endpoint: mysql://admin:Cisco2013@tcp(172.20.254.250:3306)/k3sdemo
    #k3s_use_experimental: true  # Note this is required for k3s < v1.19.5+k3s1
  roles:
    - role: xanmanning.k3s
