---

- name: 'generate initial and k3scluster inventory'
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: 'initial and k3scluster inventory'
      ansible.builtin.include_role:
        name: prerequisites
        tasks_from: inventory-generator
      vars:
        init: true
        infodata: "{{ lookup('env','DEMO') }}"
      tags:
        - init
        - k3scluster


- name: 'deploy prerequisites'
  hosts: initial
  become: yes
  gather_facts: yes
  tasks:
    - name: 'deploy prerequisites'
      ansible.builtin.include_role:
        name: prerequisites
      vars:
        init: true
        infodata: "{{ lookup('env','DEMO') }}"
      tags:
        - prereq-deploy

- name: 'generate keepalived inventory'
  hosts: initial
  become: no
  gather_facts: yes
  tasks:
    - name: 'keepalived inventory'
      ansible.builtin.include_role:
        name: prerequisites
        tasks_from: inventory-generator
      vars:
        init: true
        infodata: "{{ lookup('env','DEMO') }}"
      tags:
        - keepalived

- name: 'generate keepalived variables'
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: 'keepalived variables'
      ansible.builtin.include_role:
        name: prerequisites
        tasks_from: variables-generator
      vars:
        init: true
        infodata: "{{ lookup('env','DEMO') }}"
      tags:
        - keepalived-vars