---

- name: 'generate initial, k3scluster and keepalived inventories, generate required variables'
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: 'initial and k3scluster inventory'
      ansible.builtin.include_role:
        name: prerequisites
        tasks_from: inventory-generator
      vars:
        infodata: "{{ lookup('env','ART_HOST_INFO') }}"
      tags:
        - init
        - k3scluster
        - keepalived

    - name: 'k3s and keepalived variables'
      ansible.builtin.include_role:
        name: prerequisites
        tasks_from: variables-generator
      vars:
        infodata: "{{ lookup('env','ART_HOST_INFO') }}"
        keep_pass: "{{ lookup('env', 'KEEPPASS') }}"
        mariadb_version: "{{ lookup('env', 'MARIADB_VERSION') }}"
        mariadb_dbname: "{{ lookup('env', 'MARIADB_DBNAME') }}"
        mariadb_user: "{{ lookup('env', 'MARIADB_USER') }}"
        mariadb_password: "{{ lookup('env', 'MARIADB_PASSWORD') }}"
        mariadb_pri_domain: "{{ lookup('env', 'MARIADB_PRI_DOMAIN') }}"
        k3s_version: "{{ lookup('env', 'K3SVERSION') }}"
      tags:
        - k3scluster-vars
        - keepalived-vars

- name: 'deploy prerequisites'
  hosts: initial
  become: yes
  gather_facts: yes
  tasks:
    - name: 'deploy prerequisites'
      ansible.builtin.include_role:
        name: prerequisites
      vars:
        init: true
        infodata: "{{ lookup('env','ART_HOST_INFO') }}"
        onlyvlan: true
        netplan_configuration:
          network:
            version: 2
            ethernets:
            vlans:
      tags:
        - prereq-deploy

- name: 'mariadb cluster deployment'
  hosts: k3s_cluster
  gather_facts: yes
  vars_files:
    - vars/mariadb_vars.yml
  tags:
    - mariadb
  tasks:
    - name: 'mariadb cluster deployment process'
      ansible.builtin.include_role:
        name: eradical.ansible_mariadb_galera_cluster
      vars:
        init: true
        infodata: "{{ lookup('env','ART_HOST_INFO') }}"
        keep_pass: "{{ lookup('env', 'KEEPPASS') }}"
        mariadb_version: "{{ lookup('env', 'MARIADB_VERSION') }}"
        mariadb_dbname: "{{ lookup('env', 'MARIADB_DBNAME') }}"
        mariadb_user: "{{ lookup('env', 'MARIADB_USER') }}"
        mariadb_password: "{{ lookup('env', 'MARIADB_PASSWORD') }}"
        mariadb_pri_domain: "{{ lookup('env', 'MARIADB_PRI_DOMAIN') }}"
        k3s_version: "{{ lookup('env', 'K3SVERSION') }}"
      when:
        - k3s_control_node

- name: 'keepalived deployment'
  hosts: proxy
  gather_facts: yes
  become: true
  vars_files:
    - vars/keepalived_vars.yml
  roles:
    - role: sparknsh.keepalived
  tags:
    - keepalived-deployment
  when:
    - k3s_control_node

- name: 'k3s ha cluster deployment - external kvdb'
  hosts: k3s_cluster
  gather_facts: yes
  vars_files:
    - vars/k3s_variables.yml
  roles:
    - role: xanmanning.k3s
  tags:
    - k3s-deployment