---
- name: Install Keepalived
  include_tasks: "{{ ansible_facts['os_family'] | lower }}.yml"

- name: Copy config file
  template:
    src: master_master.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  notify: Re-start Keepalived
  when: mode == "master-master"
