---
- name: 'set hostname'
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  tags:
    - prereq-deploy

- name: 'install packages'
  dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages_redhat }}"
  tags:
    - prereq-deploy

- name: 'open firewalld ports'
  firewalld:
    port: "{{ item.port }}"
    permanent: yes
    immediate: yes
    state: "{{ item.state }}"
  loop: "{{ firewall_port_list }}"
  tags:
    - prereq-deploy

- name: 'open firewalld rich rules'
  firewalld:
    rich_rule: "rule protocol value={{ item.proto }} accept"
    permanent: yes
    immediate: yes
    state: "{{ item.state }}"
  loop: "{{ firewall_rich_rules }}"
  tags:
    - prereq-deploy

- name: 'create interface'
  nmcli:
    type: vlan
    conn_name: k3s
    ifname: "{{ vlan_name }}"
    vlandev: "{{ ansible_default_ipv4.interface }}"
    vlanid: 1
    ip4: "{{ internal_network_start | ansible.netcommon.ipmath(server_id) }}/{{ internal_cidr }}"
    autoconnect: true
    state: present
  tags:
    - prereq-deploy